version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-service
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  
  # Redis service
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"

volumes:
  mysql-data:
